AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Mumbai Local Train Dummy API for Grafana Infinity

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.11
    Environment:
      Variables:
        API_KEY: !Ref ApiKeyValue

Parameters:
  ApiKeyValue:
    Type: String
    NoEcho: true
    Default: mumbai-train-secret

Resources:
  MumbaiTrainApi:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mumbai-train-api
      CodeUri: src/
      Handler: main.handler
      Events:
        AnyRoute:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
        Root:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY

Outputs:
  ApiUrl:
    Description: Base URL
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
